# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1446250558);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1446250678);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1446269056);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1446250438);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1446272443);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "CA");
user_pref("browser.search.region", "CA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150629114848");
user_pref("browser.slowStartup.averageTime", 611);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150629114848");
user_pref("browser.startup.homepage_override.mstone", "39.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":2}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1446262959837");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1446266706360");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1446266706709");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1446353106709");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1446175181420");
user_pref("datareporting.policy.firstRunTime", "1446175120565");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 569);
user_pref("datareporting.sessions.current.main", 31);
user_pref("datareporting.sessions.current.sessionRestored", 771);
user_pref("datareporting.sessions.current.startTime", "1446272986746");
user_pref("datareporting.sessions.current.totalTime", 25);
user_pref("datareporting.sessions.currentIndex", 6);
user_pref("datareporting.sessions.previous.1", "{\"s\":1446250077452,\"a\":218,\"t\":21829,\"c\":true,\"m\":125,\"fp\":1143,\"sr\":1230}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1446272161428,\"a\":7,\"t\":34,\"c\":true,\"m\":39,\"fp\":524,\"sr\":706}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1446272260798,\"a\":11,\"t\":56,\"c\":true,\"m\":21,\"fp\":530,\"sr\":714}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1446272322460,\"a\":21,\"t\":205,\"c\":true,\"m\":20,\"fp\":548,\"sr\":735}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1446272567996,\"a\":11,\"t\":106,\"c\":true,\"m\":21,\"fp\":534,\"sr\":718}");
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1446250558);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "39.0");
user_pref("extensions.lastPlatformVersion", "39.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"41.0.2\",\"st\":1444932694000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"41.0.2\",\"st\":1444932694000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0\",\"st\":1438751766000,\"mt\":1435579394000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1438751828000,\"mt\":1420839872000}}}");
user_pref("gecko.buildID", "20150629114848");
user_pref("gecko.mstone", "39.0");
user_pref("idle.lastDailyNotification", 1446262920);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1446175183);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150629114848");
user_pref("media.gmp-manager.lastCheck", 1446272383);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1446262920);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1446262920);
user_pref("toolkit.startup.last_success", 1446272986);
user_pref("toolkit.telemetry.previousBuildID", "20150629114848");
